//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthManagementEntities : DbContext
    {
        public HealthManagementEntities()
            : base("name=HealthManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnamnesisClass> AnamnesisClass { get; set; }
        public virtual DbSet<PAnamnesis> PAnamnesis { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PData> PData { get; set; }
        public virtual DbSet<PlanOver> PlanOver { get; set; }
        public virtual DbSet<Suggest> Suggest { get; set; }
        public virtual DbSet<UPlan> UPlan { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
