//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAnamnesis
    {
        public int AnaID { get; set; }
        public Nullable<int> AClID { get; set; }
        public int PatientID { get; set; }
        public string AnaText { get; set; }
        public Nullable<System.DateTime> AnaDate { get; set; }
        public Nullable<System.DateTime> AnaCDate { get; set; }
    
        public virtual AnamnesisClass AnamnesisClass { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
