//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.PAnamnesis = new HashSet<PAnamnesis>();
            this.PData = new HashSet<PData>();
        }
    
        public int PatientID { get; set; }
        public string UserID { get; set; }
        public string PatientName { get; set; }
        public string PatientPhone { get; set; }
        public string PatientSex { get; set; }
        public Nullable<System.DateTime> PatientBirthday { get; set; }
        public Nullable<double> PatientHeight { get; set; }
        public Nullable<double> PatientWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAnamnesis> PAnamnesis { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PData> PData { get; set; }
    }
}
