//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UData
    {
        public int DataID { get; set; }
        public string UserID { get; set; }
        public string DataUName { get; set; }
        public Nullable<int> DataSex { get; set; }
        public Nullable<System.DateTime> DataBirthday { get; set; }
        public string DataPhone { get; set; }
        public string DataProfession { get; set; }
        public Nullable<double> DataHeight { get; set; }
        public Nullable<double> DataWeight { get; set; }
        public Nullable<double> BloodPressure { get; set; }
        public Nullable<double> BloodSugar { get; set; }
        public Nullable<double> BloodFat { get; set; }
        public Nullable<double> HeartRate { get; set; }
    
        public virtual User User { get; set; }
    }
}
