//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UPlan()
        {
            this.PlanOver = new HashSet<PlanOver>();
        }
    
        public int PlanID { get; set; }
        public string UserID { get; set; }
        public string PlanTitle { get; set; }
        public string PlanText { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanOver> PlanOver { get; set; }
        public virtual User User { get; set; }
    }
}
