//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Patient = new HashSet<Patient>();
            this.UPlan = new HashSet<UPlan>();
        }
    
        public string UserID { get; set; }
        public string UserPassWord { get; set; }
        public byte[] UesrImage { get; set; }
        public string UserEmail { get; set; }
        public string UserName { get; set; }
        public string UserSex { get; set; }
        public Nullable<System.DateTime> UserBirthday { get; set; }
        public string UserPhone { get; set; }
        public string UserProfession { get; set; }
        public string Hospital { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UPlan> UPlan { get; set; }
    }
}
